/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.vishaluplanch.org.schemas;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EmploymentEnrichedDetail extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4289410694481837886L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmploymentEnrichedDetail\",\"namespace\":\"com.vishaluplanch.org.schemas\",\"fields\":[{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"middleName\",\"type\":\"string\"},{\"name\":\"employmentType\",\"type\":\"string\"},{\"name\":\"inHandSalary\",\"type\":{\"type\":\"string\",\"java-class\":\"java.math.BigDecimal\"}},{\"name\":\"location\",\"type\":\"string\"},{\"name\":\"netSalary\",\"type\":{\"type\":\"string\",\"java-class\":\"java.math.BigDecimal\"}},{\"name\":\"organizationName\",\"type\":\"string\"},{\"name\":\"position\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EmploymentEnrichedDetail> ENCODER =
      new BinaryMessageEncoder<EmploymentEnrichedDetail>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EmploymentEnrichedDetail> DECODER =
      new BinaryMessageDecoder<EmploymentEnrichedDetail>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EmploymentEnrichedDetail> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EmploymentEnrichedDetail> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EmploymentEnrichedDetail>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EmploymentEnrichedDetail to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EmploymentEnrichedDetail from a ByteBuffer. */
  public static EmploymentEnrichedDetail fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence firstName;
  @Deprecated public java.lang.CharSequence lastName;
  @Deprecated public java.lang.CharSequence middleName;
  @Deprecated public java.lang.CharSequence employmentType;
  @Deprecated public java.math.BigDecimal inHandSalary;
  @Deprecated public java.lang.CharSequence location;
  @Deprecated public java.math.BigDecimal netSalary;
  @Deprecated public java.lang.CharSequence organizationName;
  @Deprecated public java.lang.CharSequence position;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EmploymentEnrichedDetail() {}

  /**
   * All-args constructor.
   * @param firstName The new value for firstName
   * @param lastName The new value for lastName
   * @param middleName The new value for middleName
   * @param employmentType The new value for employmentType
   * @param inHandSalary The new value for inHandSalary
   * @param location The new value for location
   * @param netSalary The new value for netSalary
   * @param organizationName The new value for organizationName
   * @param position The new value for position
   */
  public EmploymentEnrichedDetail(java.lang.CharSequence firstName, java.lang.CharSequence lastName, java.lang.CharSequence middleName, java.lang.CharSequence employmentType, java.math.BigDecimal inHandSalary, java.lang.CharSequence location, java.math.BigDecimal netSalary, java.lang.CharSequence organizationName, java.lang.CharSequence position) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.middleName = middleName;
    this.employmentType = employmentType;
    this.inHandSalary = inHandSalary;
    this.location = location;
    this.netSalary = netSalary;
    this.organizationName = organizationName;
    this.position = position;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return firstName;
    case 1: return lastName;
    case 2: return middleName;
    case 3: return employmentType;
    case 4: return inHandSalary;
    case 5: return location;
    case 6: return netSalary;
    case 7: return organizationName;
    case 8: return position;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: firstName = (java.lang.CharSequence)value$; break;
    case 1: lastName = (java.lang.CharSequence)value$; break;
    case 2: middleName = (java.lang.CharSequence)value$; break;
    case 3: employmentType = (java.lang.CharSequence)value$; break;
    case 4: inHandSalary = (java.math.BigDecimal)value$; break;
    case 5: location = (java.lang.CharSequence)value$; break;
    case 6: netSalary = (java.math.BigDecimal)value$; break;
    case 7: organizationName = (java.lang.CharSequence)value$; break;
    case 8: position = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return The value of the 'firstName' field.
   */
  public java.lang.CharSequence getFirstName() {
    return firstName;
  }

  /**
   * Sets the value of the 'firstName' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return The value of the 'lastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }

  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'middleName' field.
   * @return The value of the 'middleName' field.
   */
  public java.lang.CharSequence getMiddleName() {
    return middleName;
  }

  /**
   * Sets the value of the 'middleName' field.
   * @param value the value to set.
   */
  public void setMiddleName(java.lang.CharSequence value) {
    this.middleName = value;
  }

  /**
   * Gets the value of the 'employmentType' field.
   * @return The value of the 'employmentType' field.
   */
  public java.lang.CharSequence getEmploymentType() {
    return employmentType;
  }

  /**
   * Sets the value of the 'employmentType' field.
   * @param value the value to set.
   */
  public void setEmploymentType(java.lang.CharSequence value) {
    this.employmentType = value;
  }

  /**
   * Gets the value of the 'inHandSalary' field.
   * @return The value of the 'inHandSalary' field.
   */
  public java.math.BigDecimal getInHandSalary() {
    return inHandSalary;
  }

  /**
   * Sets the value of the 'inHandSalary' field.
   * @param value the value to set.
   */
  public void setInHandSalary(java.math.BigDecimal value) {
    this.inHandSalary = value;
  }

  /**
   * Gets the value of the 'location' field.
   * @return The value of the 'location' field.
   */
  public java.lang.CharSequence getLocation() {
    return location;
  }

  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(java.lang.CharSequence value) {
    this.location = value;
  }

  /**
   * Gets the value of the 'netSalary' field.
   * @return The value of the 'netSalary' field.
   */
  public java.math.BigDecimal getNetSalary() {
    return netSalary;
  }

  /**
   * Sets the value of the 'netSalary' field.
   * @param value the value to set.
   */
  public void setNetSalary(java.math.BigDecimal value) {
    this.netSalary = value;
  }

  /**
   * Gets the value of the 'organizationName' field.
   * @return The value of the 'organizationName' field.
   */
  public java.lang.CharSequence getOrganizationName() {
    return organizationName;
  }

  /**
   * Sets the value of the 'organizationName' field.
   * @param value the value to set.
   */
  public void setOrganizationName(java.lang.CharSequence value) {
    this.organizationName = value;
  }

  /**
   * Gets the value of the 'position' field.
   * @return The value of the 'position' field.
   */
  public java.lang.CharSequence getPosition() {
    return position;
  }

  /**
   * Sets the value of the 'position' field.
   * @param value the value to set.
   */
  public void setPosition(java.lang.CharSequence value) {
    this.position = value;
  }

  /**
   * Creates a new EmploymentEnrichedDetail RecordBuilder.
   * @return A new EmploymentEnrichedDetail RecordBuilder
   */
  public static com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder newBuilder() {
    return new com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder();
  }

  /**
   * Creates a new EmploymentEnrichedDetail RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmploymentEnrichedDetail RecordBuilder
   */
  public static com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder newBuilder(com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder other) {
    return new com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder(other);
  }

  /**
   * Creates a new EmploymentEnrichedDetail RecordBuilder by copying an existing EmploymentEnrichedDetail instance.
   * @param other The existing instance to copy.
   * @return A new EmploymentEnrichedDetail RecordBuilder
   */
  public static com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder newBuilder(com.vishaluplanch.org.schemas.EmploymentEnrichedDetail other) {
    return new com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder(other);
  }

  /**
   * RecordBuilder for EmploymentEnrichedDetail instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmploymentEnrichedDetail>
    implements org.apache.avro.data.RecordBuilder<EmploymentEnrichedDetail> {

    private java.lang.CharSequence firstName;
    private java.lang.CharSequence lastName;
    private java.lang.CharSequence middleName;
    private java.lang.CharSequence employmentType;
    private java.math.BigDecimal inHandSalary;
    private java.lang.CharSequence location;
    private java.math.BigDecimal netSalary;
    private java.lang.CharSequence organizationName;
    private java.lang.CharSequence position;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.firstName)) {
        this.firstName = data().deepCopy(fields()[0].schema(), other.firstName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lastName)) {
        this.lastName = data().deepCopy(fields()[1].schema(), other.lastName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.middleName)) {
        this.middleName = data().deepCopy(fields()[2].schema(), other.middleName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.employmentType)) {
        this.employmentType = data().deepCopy(fields()[3].schema(), other.employmentType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.inHandSalary)) {
        this.inHandSalary = data().deepCopy(fields()[4].schema(), other.inHandSalary);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.location)) {
        this.location = data().deepCopy(fields()[5].schema(), other.location);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.netSalary)) {
        this.netSalary = data().deepCopy(fields()[6].schema(), other.netSalary);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.organizationName)) {
        this.organizationName = data().deepCopy(fields()[7].schema(), other.organizationName);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.position)) {
        this.position = data().deepCopy(fields()[8].schema(), other.position);
        fieldSetFlags()[8] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EmploymentEnrichedDetail instance
     * @param other The existing instance to copy.
     */
    private Builder(com.vishaluplanch.org.schemas.EmploymentEnrichedDetail other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.firstName)) {
        this.firstName = data().deepCopy(fields()[0].schema(), other.firstName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lastName)) {
        this.lastName = data().deepCopy(fields()[1].schema(), other.lastName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.middleName)) {
        this.middleName = data().deepCopy(fields()[2].schema(), other.middleName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.employmentType)) {
        this.employmentType = data().deepCopy(fields()[3].schema(), other.employmentType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.inHandSalary)) {
        this.inHandSalary = data().deepCopy(fields()[4].schema(), other.inHandSalary);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.location)) {
        this.location = data().deepCopy(fields()[5].schema(), other.location);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.netSalary)) {
        this.netSalary = data().deepCopy(fields()[6].schema(), other.netSalary);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.organizationName)) {
        this.organizationName = data().deepCopy(fields()[7].schema(), other.organizationName);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.position)) {
        this.position = data().deepCopy(fields()[8].schema(), other.position);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'firstName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstName() {
      return firstName;
    }

    /**
      * Sets the value of the 'firstName' field.
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.firstName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'firstName' field.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }

    /**
      * Sets the value of the 'lastName' field.
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.lastName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lastName' field.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'middleName' field.
      * @return The value.
      */
    public java.lang.CharSequence getMiddleName() {
      return middleName;
    }

    /**
      * Sets the value of the 'middleName' field.
      * @param value The value of 'middleName'.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder setMiddleName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.middleName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'middleName' field has been set.
      * @return True if the 'middleName' field has been set, false otherwise.
      */
    public boolean hasMiddleName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'middleName' field.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder clearMiddleName() {
      middleName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'employmentType' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmploymentType() {
      return employmentType;
    }

    /**
      * Sets the value of the 'employmentType' field.
      * @param value The value of 'employmentType'.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder setEmploymentType(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.employmentType = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'employmentType' field has been set.
      * @return True if the 'employmentType' field has been set, false otherwise.
      */
    public boolean hasEmploymentType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'employmentType' field.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder clearEmploymentType() {
      employmentType = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'inHandSalary' field.
      * @return The value.
      */
    public java.math.BigDecimal getInHandSalary() {
      return inHandSalary;
    }

    /**
      * Sets the value of the 'inHandSalary' field.
      * @param value The value of 'inHandSalary'.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder setInHandSalary(java.math.BigDecimal value) {
      validate(fields()[4], value);
      this.inHandSalary = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'inHandSalary' field has been set.
      * @return True if the 'inHandSalary' field has been set, false otherwise.
      */
    public boolean hasInHandSalary() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'inHandSalary' field.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder clearInHandSalary() {
      inHandSalary = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'location' field.
      * @return The value.
      */
    public java.lang.CharSequence getLocation() {
      return location;
    }

    /**
      * Sets the value of the 'location' field.
      * @param value The value of 'location'.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder setLocation(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.location = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'location' field.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder clearLocation() {
      location = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'netSalary' field.
      * @return The value.
      */
    public java.math.BigDecimal getNetSalary() {
      return netSalary;
    }

    /**
      * Sets the value of the 'netSalary' field.
      * @param value The value of 'netSalary'.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder setNetSalary(java.math.BigDecimal value) {
      validate(fields()[6], value);
      this.netSalary = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'netSalary' field has been set.
      * @return True if the 'netSalary' field has been set, false otherwise.
      */
    public boolean hasNetSalary() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'netSalary' field.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder clearNetSalary() {
      netSalary = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'organizationName' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrganizationName() {
      return organizationName;
    }

    /**
      * Sets the value of the 'organizationName' field.
      * @param value The value of 'organizationName'.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder setOrganizationName(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.organizationName = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'organizationName' field has been set.
      * @return True if the 'organizationName' field has been set, false otherwise.
      */
    public boolean hasOrganizationName() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'organizationName' field.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder clearOrganizationName() {
      organizationName = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'position' field.
      * @return The value.
      */
    public java.lang.CharSequence getPosition() {
      return position;
    }

    /**
      * Sets the value of the 'position' field.
      * @param value The value of 'position'.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder setPosition(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.position = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'position' field has been set.
      * @return True if the 'position' field has been set, false otherwise.
      */
    public boolean hasPosition() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'position' field.
      * @return This builder.
      */
    public com.vishaluplanch.org.schemas.EmploymentEnrichedDetail.Builder clearPosition() {
      position = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EmploymentEnrichedDetail build() {
      try {
        EmploymentEnrichedDetail record = new EmploymentEnrichedDetail();
        record.firstName = fieldSetFlags()[0] ? this.firstName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.lastName = fieldSetFlags()[1] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.middleName = fieldSetFlags()[2] ? this.middleName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.employmentType = fieldSetFlags()[3] ? this.employmentType : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.inHandSalary = fieldSetFlags()[4] ? this.inHandSalary : (java.math.BigDecimal) defaultValue(fields()[4]);
        record.location = fieldSetFlags()[5] ? this.location : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.netSalary = fieldSetFlags()[6] ? this.netSalary : (java.math.BigDecimal) defaultValue(fields()[6]);
        record.organizationName = fieldSetFlags()[7] ? this.organizationName : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.position = fieldSetFlags()[8] ? this.position : (java.lang.CharSequence) defaultValue(fields()[8]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EmploymentEnrichedDetail>
    WRITER$ = (org.apache.avro.io.DatumWriter<EmploymentEnrichedDetail>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EmploymentEnrichedDetail>
    READER$ = (org.apache.avro.io.DatumReader<EmploymentEnrichedDetail>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
