/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.vishaluplanch.kafka.avro.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class StockPriceSumAndCount extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2896617987287560530L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StockPriceSumAndCount\",\"namespace\":\"com.vishaluplanch.kafka.avro.schema\",\"fields\":[{\"name\":\"count\",\"type\":\"long\",\"default\":-1},{\"name\":\"sum\",\"type\":\"double\",\"default\":0.0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StockPriceSumAndCount> ENCODER =
      new BinaryMessageEncoder<StockPriceSumAndCount>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StockPriceSumAndCount> DECODER =
      new BinaryMessageDecoder<StockPriceSumAndCount>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<StockPriceSumAndCount> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<StockPriceSumAndCount> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<StockPriceSumAndCount>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this StockPriceSumAndCount to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a StockPriceSumAndCount from a ByteBuffer. */
  public static StockPriceSumAndCount fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long count;
  @Deprecated public double sum;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StockPriceSumAndCount() {}

  /**
   * All-args constructor.
   * @param count The new value for count
   * @param sum The new value for sum
   */
  public StockPriceSumAndCount(java.lang.Long count, java.lang.Double sum) {
    this.count = count;
    this.sum = sum;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return count;
    case 1: return sum;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: count = (java.lang.Long)value$; break;
    case 1: sum = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'count' field.
   * @return The value of the 'count' field.
   */
  public java.lang.Long getCount() {
    return count;
  }

  /**
   * Sets the value of the 'count' field.
   * @param value the value to set.
   */
  public void setCount(java.lang.Long value) {
    this.count = value;
  }

  /**
   * Gets the value of the 'sum' field.
   * @return The value of the 'sum' field.
   */
  public java.lang.Double getSum() {
    return sum;
  }

  /**
   * Sets the value of the 'sum' field.
   * @param value the value to set.
   */
  public void setSum(java.lang.Double value) {
    this.sum = value;
  }

  /**
   * Creates a new StockPriceSumAndCount RecordBuilder.
   * @return A new StockPriceSumAndCount RecordBuilder
   */
  public static com.vishaluplanch.kafka.avro.schema.StockPriceSumAndCount.Builder newBuilder() {
    return new com.vishaluplanch.kafka.avro.schema.StockPriceSumAndCount.Builder();
  }

  /**
   * Creates a new StockPriceSumAndCount RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StockPriceSumAndCount RecordBuilder
   */
  public static com.vishaluplanch.kafka.avro.schema.StockPriceSumAndCount.Builder newBuilder(com.vishaluplanch.kafka.avro.schema.StockPriceSumAndCount.Builder other) {
    return new com.vishaluplanch.kafka.avro.schema.StockPriceSumAndCount.Builder(other);
  }

  /**
   * Creates a new StockPriceSumAndCount RecordBuilder by copying an existing StockPriceSumAndCount instance.
   * @param other The existing instance to copy.
   * @return A new StockPriceSumAndCount RecordBuilder
   */
  public static com.vishaluplanch.kafka.avro.schema.StockPriceSumAndCount.Builder newBuilder(com.vishaluplanch.kafka.avro.schema.StockPriceSumAndCount other) {
    return new com.vishaluplanch.kafka.avro.schema.StockPriceSumAndCount.Builder(other);
  }

  /**
   * RecordBuilder for StockPriceSumAndCount instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StockPriceSumAndCount>
    implements org.apache.avro.data.RecordBuilder<StockPriceSumAndCount> {

    private long count;
    private double sum;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.vishaluplanch.kafka.avro.schema.StockPriceSumAndCount.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.count)) {
        this.count = data().deepCopy(fields()[0].schema(), other.count);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sum)) {
        this.sum = data().deepCopy(fields()[1].schema(), other.sum);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing StockPriceSumAndCount instance
     * @param other The existing instance to copy.
     */
    private Builder(com.vishaluplanch.kafka.avro.schema.StockPriceSumAndCount other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.count)) {
        this.count = data().deepCopy(fields()[0].schema(), other.count);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sum)) {
        this.sum = data().deepCopy(fields()[1].schema(), other.sum);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'count' field.
      * @return The value.
      */
    public java.lang.Long getCount() {
      return count;
    }

    /**
      * Sets the value of the 'count' field.
      * @param value The value of 'count'.
      * @return This builder.
      */
    public com.vishaluplanch.kafka.avro.schema.StockPriceSumAndCount.Builder setCount(long value) {
      validate(fields()[0], value);
      this.count = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'count' field has been set.
      * @return True if the 'count' field has been set, false otherwise.
      */
    public boolean hasCount() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'count' field.
      * @return This builder.
      */
    public com.vishaluplanch.kafka.avro.schema.StockPriceSumAndCount.Builder clearCount() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sum' field.
      * @return The value.
      */
    public java.lang.Double getSum() {
      return sum;
    }

    /**
      * Sets the value of the 'sum' field.
      * @param value The value of 'sum'.
      * @return This builder.
      */
    public com.vishaluplanch.kafka.avro.schema.StockPriceSumAndCount.Builder setSum(double value) {
      validate(fields()[1], value);
      this.sum = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sum' field has been set.
      * @return True if the 'sum' field has been set, false otherwise.
      */
    public boolean hasSum() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sum' field.
      * @return This builder.
      */
    public com.vishaluplanch.kafka.avro.schema.StockPriceSumAndCount.Builder clearSum() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StockPriceSumAndCount build() {
      try {
        StockPriceSumAndCount record = new StockPriceSumAndCount();
        record.count = fieldSetFlags()[0] ? this.count : (java.lang.Long) defaultValue(fields()[0]);
        record.sum = fieldSetFlags()[1] ? this.sum : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StockPriceSumAndCount>
    WRITER$ = (org.apache.avro.io.DatumWriter<StockPriceSumAndCount>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StockPriceSumAndCount>
    READER$ = (org.apache.avro.io.DatumReader<StockPriceSumAndCount>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
